config/routes.rb
Wl::Application.routes.draw do

  resources :places do
    resources :workouts do
      resources :exercise_items
    end
    resources :exercises
  end

  root 'pages#home'

  get 'home', to: 'devise/sessions#new', as: 'home'

  devise_for :users

  namespace :admin do
    root 'base#index'
    resources :users
  end

  namespace :api do
    scope :v1 do
      resources :users, only: :create
      resources :sessions, only: :create
      resources :workouts, only: %i(index show destroy)
      resources :places, except: %i(new edit update) do
        resources :workouts, only: %i(index create)
      end
    end
  end
end

app/models/exercise_item.rb
class ExerciseItem < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise

  validates :exercise,  presence: true
  validates :repeats_count, presence: true, numericality: { greater_than: 0 }
  validates :weight, numericality: { greater_than: 0 }, allow_blank: true

  delegate :name, allow_nil: true, prefix: true, to: :exercise
end

app/controllers/exercise_items_controller.rb
class ExerciseItemsController < ApplicationController
  before_action :load_place_and_workout
  before_action :set_exercise_item, only: [:show, :edit, :update, :destroy]

  def index
    @exercise_items = ExerciseItem.all
    respond_with(@exercise_items)
  end

  def show
    respond_with(@exercise_item)
  end

  def new
    @exercise_item = ExerciseItem.new
    respond_with(@exercise_item)
  end

  def edit
  end

  def create
    @exercise_item = @workout.exercise_items.build(exercise_item_params)
    if @exercise_item.save
      redirect_to [@place, @workout]
    else
      render :new
    end
  end

  def update
    @exercise_item.update(exercise_item_params)
    respond_with(@exercise_item)
  end

  def destroy
    @exercise_item.destroy
    respond_with(@exercise_item)
  end

  private

  def load_place_and_workout
    @place = current_user.places.find(params[:place_id])
    @workout = @place.workouts.find(params[:workout_id])
  end

  def set_exercise_item
    @exercise_item = ExerciseItem.find(params[:id])
  end

  def exercise_item_params
    params.require(:exercise_item).permit(:workout_id, :exercise_id, :time, :repeats_count, :weight)
  end
end

app/helpers/exercise_items_helper.rb
module ExerciseItemsHelper
end

app/views/exercise_items/_exercise_item.html.haml
%div
  Exercise:
  = exercise_item.exercise_name
  Repeats count:
  = exercise_item.repeats_count
  - if exercise_item.weight
    Weight:
    = exercise_item.weight

app/views/exercise_items/_form.html.haml
= form_for [@place, @workout, @exercise_item] do |f|
  - if @exercise_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exercise_item.errors.count, "error")} prohibited this exercise_item from being saved:"
      %ul
        - @exercise_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :exercise
    = f.select :exercise_id, @place.exercises.map {|ex| [ex.name, ex.id, {'data-need-weight' => ex.need_weight?}] }
  .field
    = f.label :repeats_count
    = f.number_field :repeats_count
  .field{'data-scope'=>'weight'}
    = f.label :weight
    = f.number_field :weight
  .field
    = f.label :time
    %span
      (in seconds. Optional)
    = f.number_field :time
  .actions
    = f.submit 'Save'

app/views/exercise_items/edit.html.haml
%h1 Editing exercise_item

= render 'form'

= link_to 'Show', @exercise_item
\|
= link_to 'Back', exercise_items_path

app/views/exercise_items/index.html.haml
%h1 Listing exercise_items

%table
  %tr
    %th Workout
    %th Exercise
    %th Time
    %th Repeats count
    %th Weight
    %th
    %th
    %th

  - @exercise_items.each do |exercise_item|
    %tr
      %td= exercise_item.workout
      %td= exercise_item.exercise
      %td= exercise_item.time
      %td= exercise_item.repeats_count
      %td= exercise_item.weight
      %td= link_to 'Show', exercise_item
      %td= link_to 'Edit', edit_exercise_item_path(exercise_item)
      %td= link_to 'Destroy', exercise_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Exercise item', new_exercise_item_path

app/views/exercise_items/new.html.haml
%h1 New exercise item

= render 'form'

= link_to 'Back', [@place, @workout]

app/views/exercise_items/show.html.haml
%p#notice= notice

%p
  %b Workout:
  = @exercise_item.workout
%p
  %b Exercise:
  = @exercise_item.exercise
%p
  %b Time:
  = @exercise_item.time
%p
  %b Repeats count:
  = @exercise_item.repeats_count
%p
  %b Weight:
  = @exercise_item.weight

= link_to 'Edit', edit_exercise_item_path(@exercise_item)
\|
= link_to 'Back', exercise_items_path