config/routes.rb
Wl::Application.routes.draw do

  resources :places do
    resources :workouts do
      resources :exercise_items
    end
    resources :exercises
  end

  root 'pages#home'

  get 'home', to: 'devise/sessions#new', as: 'home'

  devise_for :users

  namespace :admin do
    root 'base#index'
    resources :users
  end

  namespace :api do
    scope :v1 do
      resources :users, only: :create
      resources :sessions, only: :create
      resources :workouts, only: %i(index show destroy)
      resources :places, except: %i(new edit update) do
        resources :workouts, only: %i(index create)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Pagination
  paginates_per 100

  has_many :places
  has_many :workouts, through: :places

  # Validations
  with_options presence: true do |pt|
    pt.validates :first_name
    pt.validates :last_name
  end

  # Callbacks
  before_save :ensure_access_token

  class << self
    def paged(page_number)
      order(admin: :desc, email: :asc).page page_number
    end

    def search_and_order(search, page_number)
      (search ? where('email LIKE ?', "%#{search.downcase}%") : all).paged(page_number)
    end

    def last_signups(count)
      order(created_at: :desc).limit(count).select(:id, :email, :created_at)
    end

    def last_signins(count)
      order(last_sign_in_at: :desc).limit(count).select(:id, :email, :last_sign_in_at)
    end

    def users_count
      where(admin: false, locked: false).count
    end
  end

  private

  def ensure_access_token
    self.access_token ||= generate_access_token
  end

  def generate_access_token
    loop do
      token = Devise.friendly_token
      break token unless self.class.where(access_token: token).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def edit
  end

  def update
    old_email = @user.email
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip

    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0

    if current_user.id != @user.id
      @user.admin = new_params[:admin] == '0' ? false : true
      @user.locked = new_params[:locked] == '0' ? false : true
    end

    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      flash[:alert] = "#{old_email} couldn't be updated."
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  skip_before_action :verify_access_token

  def create
    @user = User.new(user_params)
    @user.skip_confirmation!
    @user.save

    respond_with(@user, location: nil)
  end

  private

  def user_params
    params.require(:user).permit(*%i(email password first_name last_name))
  end
end

app/views/admin/users/edit.html.haml
- title("Edit User Id: #{@user.id}")
.row
  .col-sm-6
    %h1
      Edit User
      %small= "#{@user.email} - id: #{@user.id}"
    %p= link_to "Back to Users", admin_users_path
    = form_for [:admin, @user], :html => { :role => "form" } do |f|
      .form-group
        = f.label :email
        .row
          .col-sm-6
            = f.email_field :email, class: "form-control"
      .form-group
        = f.label :password
        .row
          .col-sm-6
            = f.password_field :password, class: "form-control"
      .form-group
        = f.label :password_confirmation
        .row
          .col-sm-6
            = f.password_field :password_confirmation, class: "form-control"
      - unless current_user.id == @user.id
        .form-group
          .row
            .col-sm-6
              = f.check_box :locked
              = f.label :locked, "Is Locked?"
        .form-group
          .row
            .col-sm-6
              = f.check_box :admin
              = f.label :admin, "Is Admin?"
      .row
        .col-sm-6
          = f.submit "Update User", class: "btn btn-danger"

app/views/admin/users/index.html.haml
- title("Users Admin")
%h1
  Users
  %small Admin
%p= link_to "Back to Admin", admin_root_path
.text-center
  %p= page_entries_info @users
  = paginate @users
= form_tag admin_users_path, method: 'get', html: {role: "form"} do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary"
    = link_to "All", admin_users_path, {class: "btn btn-sm btn-link"}
%table.table.table-striped
  %tr
    %th User ID
    %th Admin
    %th Locked
    %th Email
    %th Sign In Count
    %th Created At
    %th Last Sign In
    %th Last Sign In IP
  - @users.each do |user|
    %tr
      %td= user.id
      %td= link_to user.email, admin_user_path(user)
      %td= user.admin? ? "<b>yes</b>".html_safe : "no"
      %td= user.locked? ? "<b>yes</b>".html_safe : "no"
      %td= user.sign_in_count
      %td= time_ago_in_words(user.created_at)
      - unless user.last_sign_in_at.nil?
        %td
          = time_ago_in_words(user.last_sign_in_at)
          ago
      - else
        %td never
      %td= user.last_sign_in_ip
.text-center
  %p= page_entries_info @users
  = paginate @users