config/routes.rb
Wl::Application.routes.draw do

  resources :places do
    resources :workouts do
      resources :exercise_items
    end
    resources :exercises
  end

  root 'pages#home'

  get 'home', to: 'devise/sessions#new', as: 'home'

  devise_for :users

  namespace :admin do
    root 'base#index'
    resources :users
  end

  namespace :api do
    scope :v1 do
      resources :users, only: :create
      resources :sessions, only: :create
      resources :workouts, only: %i(index show destroy)
      resources :places, except: %i(new edit update) do
        resources :workouts, only: %i(index create)
      end
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :load_place
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = @place.exercises
    respond_with(@exercises)
  end

  def show
    respond_with(@exercise)
  end

  def new
    @exercise = Exercise.new
    respond_with(@exercise)
  end

  def edit
  end

  def create
    @exercise = @place.exercises.build(exercise_params)
    if @exercise.save
      respond_with([@place, @exercise])
    else
      render :new
    end
  end

  def update
    if @exercise.update(exercise_params)
      respond_with([@place, @exercise])
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    respond_with([@place, @exercise])
  end

  private

  def load_place
    @place = current_user.places.find(params[:place_id])
  end

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :values_type, :place_id, :muscle_group)
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.haml
= form_for([@place, @exercise]) do |f|
  - if @exercise.errors.any?
    #error_explanation
      %h2
        = pluralize(@exercise.errors.count, "error")
        prohibited this exercise from being saved:
      %ul
        - @exercise.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :muscle_group
    %br/
    = f.select :muscle_group, Exercise::MUSCLE_GROUPS
  .field
    = f.label :values_type
    %br
      %div
        Only times - we just need track times of execution. Example: Push ups, squats, etc
      %div
        Times and weights - we need know weight of inventory and times of execution: dumbbells, barbell
    %br
    = f.select :values_type, Exercise::VALUES_TYPES
  %br/
  .actions
    = f.submit

app/views/exercises/edit.html.haml
%h1 Editing exercise
= render 'form'
= link_to 'Show', [@place, @exercise]
|
\#{link_to 'Back', place_exercises_path(@place)}

app/views/exercises/index.html.haml
%h1 Listing exercises
%table
  %thead
    %tr
      %th Name
      %th Values type
      %th{:colspan => "3"}
  %tbody
    - @exercises.each do |exercise|
      %tr
        %td= exercise.name
        %td= exercise.values_type
        %td= link_to 'Show', [@place,exercise]
        %td= link_to 'Edit', edit_place_exercise_path(@place,exercise)
        %td= link_to 'Destroy', [@place, exercise], method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Exercise', new_place_exercise_path(@place)

app/views/exercises/new.html.haml
%h1 New exercise
= render 'form'
= link_to 'Back', place_exercises_path(@place)

app/views/exercises/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @exercise.name
%p
  %strong Values type:
  = @exercise.values_type
= link_to 'Edit', edit_place_exercise_path(@place, @exercise)
|
\#{link_to 'Back', place_exercises_path(@place)}