config/routes.rb
Wl::Application.routes.draw do

  resources :places do
    resources :workouts do
      resources :exercise_items
    end
    resources :exercises
  end

  root 'pages#home'

  get 'home', to: 'devise/sessions#new', as: 'home'

  devise_for :users

  namespace :admin do
    root 'base#index'
    resources :users
  end

  namespace :api do
    scope :v1 do
      resources :users, only: :create
      resources :sessions, only: :create
      resources :workouts, only: %i(index show destroy)
      resources :places, except: %i(new edit update) do
        resources :workouts, only: %i(index create)
      end
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :exercises
  has_many :workouts

  include CommonApiScopes
  validates :name, presence: true

  def current_workout
    @current_workout ||= workouts.where(date: Date.current).sorted.first
  end
end

app/controllers/api/places_controller.rb
class Api::PlacesController < ApiController
  before_action :load_place, only: %i(show destroy)

  def index
    @places = current_user.places.limit_with(params[:limit]).load
  end

  def show
  end

  def create
    @place = current_user.places.create(place_params)
    respond_with(@place, location: nil)
  end

  def destroy
    @place.destroy
    render json: { success: @place.destroyed? }
  end

  private

  def place_params
    params.require(:place).permit(*%i(name description))
  end

  def load_place
    @place = current_user.places.find(params[:id])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  respond_to :html
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = current_user.places
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    @place = current_user.places.build
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = current_user.places.build(place_params)
    @place.save
    respond_with(@place)
  end

  def update
    @place.update(place_params)
    respond_with(@place)
  end

  def destroy
    @place.destroy
    respond_with(@place)
  end

  private

  def set_place
    @place = current_user.places.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :description)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @places.each do |place|
    %tr
      %td= place.name
      %td= place.description
      %td= link_to 'Show', place
      %td= link_to 'Edit', edit_place_path(place)
      %td= link_to 'Destroy', place, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @place.name
%p
  %b Description:
  = @place.description

%h3 Workouts
= render @place.workouts
%hr/
= render 'workouts/form'